### ISSUE TITLE
VO starts playing when attempting to start game with no players connected

### ISSUE THREAD

**Issue by homsar** [very-scary-scenario/fixed#16]
when clicking "Everyone is here! Go!" when no players have connected, a message is displayed requesting the host wait until players are connected.

expected: clicking OK here returns the state to as it was before the "Go!" button was clicked, with the game not begun

actual: the voiceover begins playing as if the game has started, but other state is reset.

**Comment by colons** [comment]
i believe that this was fixed in e6d25c6849283f838e872942fc56c7eed463a6a3
